#  This is a docker image for the helmsman test container
#  It can be pulled from praqma/helmsman-test

ARG GO_VERSION=1.13.5
ARG KUBE_VERSION
ARG HELM_VERSION

FROM golang:${GO_VERSION}-alpine3.10

ENV KUBE_VERSION ${KUBE_VERSION:-v1.14.8}
ENV HELM_VERSION ${HELM_VERSION:-v3.0.1}
ENV GORELEASER_VERSION ${GORELEASER_VERSION:-v0.120.2}
RUN apk --no-cache update \
    && apk add --update --no-cache ca-certificates git ruby \
    && apk add --update -t deps curl tar gzip make bash gcc git dep openssh \
    && rm -rf /var/cache/apk/* \
    && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && curl -L https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar zxv -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/linux-amd64 \
    && chmod +x /usr/local/bin/helm

WORKDIR src/helmsman

RUN mkdir -p ~/.helm/plugins \
    && helm plugin install https://github.com/hypnoglow/helm-s3.git \
    && helm plugin install https://github.com/nouney/helm-gcs \
    && helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7 \
    && helm plugin install https://github.com/futuresimple/helm-secrets \
    && rm -r /tmp/helm-diff /tmp/helm-diff.tgz \
    && gem install hiera-eyaml --no-doc

RUN  mkdir /tmp/goreleaser \
     && curl -L https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/goreleaser_Linux_arm64.tar.gz | tar zxv -C /tmp/goreleaser \
     && mv /tmp/goreleaser/goreleaser /usr/local/bin/goreleaser \
     && rm -r /tmp/goreleaser \
     && chmod +x /usr/local/bin/goreleaser \
     && go get github.com/golang/dep/cmd/dep
