#  This is a docker image for the helmsman test container
#  It can be pulled from praqma/helmsman-test
FROM golang:1.8-alpine3.6 as builder

ENV KUBE_LATEST_VERSION v1.8.2
ENV HELM_VERSION v2.7.0

RUN apk add --update ca-certificates \
    && apk add --update -t deps curl \
    && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl 

RUN apk add --update --no-cache ca-certificates git \
    && apk add --update -t deps curl tar gzip make bash \
    && curl -L http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar zxv -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && rm -rf /tmp/linux-amd64
    
RUN go get github.com/BurntSushi/toml \ 
    && go get github.com/goreleaser/goreleaser \
    && go get github.com/Praqma/helmsman/gcs

WORKDIR src/helmsman    