#  This is a docker image for the helmsman test container
#  It can be pulled from praqma/helmsman-test
FROM golang:1.10-alpine3.7 as builder

ENV KUBE_VERSION v1.8.2
ENV HELM_VERSION v2.10.0

RUN apk add --update --no-cache ca-certificates git \
    && apk add --update -t deps curl tar gzip make bash \
    && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && curl -L http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar zxv -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/linux-amd64 \
    && chmod +x /usr/local/bin/helm

WORKDIR src/helmsman

RUN adduser -D -g '' helmsman && \
    chown -R helmsman /go

USER helmsman

RUN  mkdir -p ~/.helm/plugins \
    && helm plugin install https://github.com/databus23/helm-diff

RUN go get github.com/goreleaser/goreleaser && \
    go get github.com/golang/dep/cmd/dep
