FROM golang:1.9 as builder
WORKDIR /go/src/
RUN go get github.com/BurntSushi/toml  
RUN git clone https://github.com/Praqma/helmsman.git 
RUN go install helmsman/.

FROM alpine:3.6 as kube
ENV KUBE_LATEST_VERSION="v1.8.2"

RUN apk add --update ca-certificates 
RUN apk add --update -t deps curl 
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl 
RUN chmod +x /usr/local/bin/kubectl 

# The image to keep
FROM alpine:3.6 
RUN apk add --update --no-cache ca-certificates git

ENV VERSION v2.7.0

WORKDIR /

RUN apk add --update -t deps curl tar gzip make bash \
    && curl -L http://storage.googleapis.com/kubernetes-helm/helm-${VERSION}-linux-amd64.tar.gz | tar zxv -C /tmp \
    && mv /tmp/linux-amd64/helm /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm \
    && mkdir -p ~/.helm/plugins \
    && helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.4.0 \
    && rm -rf /tmp/linux-amd64

COPY --from=kube /usr/local/bin/kubectl /bin/kubectl
COPY --from=builder /go/bin/helmsman   /bin/helmsman

ENTRYPOINT ["/bin/helmsman"]
 
